'use client';
import ProjectDetails from './project-details';
import Method from './method';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,Activity,GitBranch,Layers,SlidersHorizontal,BookOpen,Download,Upload,ChevronDown,Check,Clock,FileText,Scale,Info,RotateCcw,X} from 'lucide-react';
import {actions,comparable,demo,enumerate,frontier,parseCase,project,stateAt,runModel,modelIds,DEFAULT_MODEL,type ModelKind,type Action,type CaseData,type Projection} from '../lib/model';
import {publicCases} from '../lib/cases';
import {productVersion} from '../lib/version';
type View='live'|'path'|'compare'|'frontier'|'method';
const money=(v:number|null)=>v===null?'—':'$'+Math.round(v).toLocaleString('en-US');
const compact=(v:number)=>'$'+(v/1000).toFixed(v%1000===0?0:1)+'k';
const pct=(v:number)=>(v*100).toFixed(0)+'%';
const viewNames:Record<View,[string,string]>={compare:['Compare paths','比较路径'],path:['Case record','案件记录'],live:['Overview','概览'],frontier:['Explore alternatives','其他方案'],method:['Method','方法']};
const icons={live:Activity,path:GitBranch,compare:Layers,frontier:SlidersHorizontal,method:BookOpen};
function download(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function Page(){
 const [view,setView]=useState<View>('compare'),[zh,setZh]=useState(false),[data,setData]=useState<CaseData>(publicCases[0]),[index,setIndex]=useState(publicCases[0].events.length-2),[selectedEvent,setSelectedEvent]=useState(publicCases[0].events.length-2),[horizon,setHorizon]=useState(3),[epsilon,setEpsilon]=useState(.02),[swapped,setSwapped]=useState(false),[review,setReview]=useState(false),[notice,setNotice]=useState(''),[importOpen,setImportOpen]=useState(false),[highlight,setHighlight]=useState<Projection|null>(null);
 const modelKind=DEFAULT_MODEL;
 const [execution,setExecution]=useState<{key:string;result:ReturnType<typeof runModel>}|null>(null);
 const loadCase=(next:CaseData)=>{setData(next);setIndex(Math.max(0,next.events.length-2));setSelectedEvent(Math.max(0,next.events.length-2));setSwapped(false);setReview(false);setHighlight(null);setExecution(null);setNotice('');};
 const upload=useRef<HTMLInputElement>(null);const t=(en:string,cn:string)=>zh?cn:en;
 const state=stateAt(data,index),all=enumerate(state.information,modelKind),edge=frontier(all),comparison=comparable(state.information,epsilon,modelKind),continuation=comparison.baseline;
 const a=swapped?comparison.baseline:comparison.best,b=swapped?comparison.best:comparison.baseline,pathA=a.path,pathB=b.path;
 const runKey=JSON.stringify([data,index,epsilon,pathA,pathB,modelKind]),currentRun=execution?.key===runKey?execution.result:null;
 const label=(id:Action)=>zh?actions[id].zh:actions[id].label;
 useEffect(()=>{const id=window.location.hash.slice(1) as View;if(id in viewNames)setView(id);const lang=new URLSearchParams(window.location.search).get('lang');if(lang==='zh')setZh(true);else if(lang==='en')setZh(false);},[]);
 useEffect(()=>{document.documentElement.lang=zh?'zh-CN':'en';},[zh]);
 const changeLanguage=(value:boolean)=>{setZh(value);try{localStorage.setItem('secondorder-site-language',value?'zh':'en');}catch{}};
 const navigate=(v:View)=>{setView(v);history.replaceState(null,'','#'+v);setNotice('');};
 const exportSnapshot=()=>{download('secondorder-procedure-snapshot.json',{schemaVersion:1,case:data.name,synthetic:data.synthetic,asOfDay:state.day,events:state.events,model:modelIds[modelKind],modelKind,version:productVersion,publicRecord:data.publicRecord??false,run:currentRun,validated:false,baseline:continuation,pathA:a,pathB:b,tolerance:epsilon,comparison});setNotice(t('Snapshot exported. Includes only events through the selected day.','已导出时间切片，仅包含截至所选日期的事件。'));};
 const importFile=async(file:File)=>{try{if(file.size>1024*1024)throw Error('Maximum file size is 1 MB.');const next=parseCase(JSON.parse(await file.text()));loadCase(next);setImportOpen(false);setNotice(t('Case imported locally. Projections still use demonstration rules.','案件已在本地导入，推演仍使用演示规则。'));}catch(e){setNotice(e instanceof Error?e.message:'Unable to import case.');}if(upload.current)upload.current.value='';};
 const kpi=(title:string,value:string,detail:string,kind='estimate')=><article className="kpi"><span className="kpi-label">{title}<i className={kind==='observed'?'observed':'estimated'}>{kind==='observed'?t('RECORD','记录'):t('ILLUSTRATIVE','示例')}</i></span><strong>{value}</strong><small>{detail}</small></article>;
 const panelHead=(n:string,title:string,extra?:React.ReactNode)=><div className="panel-head"><h2><span>{n}</span>{title}</h2>{extra}</div>;
 return <div className="app-shell">
 <header className="topbar"><a className="brand so-brand" href="#compare" onClick={e=>{e.preventDefault();navigate('compare');}}><span className="so-brand-mark" aria-hidden="true">II</span><span className="so-brand-copy">SecondOrder Procedure{zh && <small>二阶效应</small>}</span></a><ProjectDetails zh={zh} /><div className="top-right"><span className="version">{productVersion}</span><div className="language" aria-label="Language"><button className={!zh?'active':''} onClick={()=>changeLanguage(false)} aria-pressed={!zh}>EN</button><button className={zh?'active':''} onClick={()=>changeLanguage(true)} aria-pressed={zh}>中文</button></div></div></header>
 <div className="workspace">
 <aside className="sidebar"><div className="workspace-label">{t('LITIGATION WORKSPACE','诉讼工作台')}</div><div className="case-card"><span className="case-symbol"><Scale size={19}/></span><div><strong>{data.name}</strong><small>{t('Discovery phase','证据开示阶段')}</small></div></div><label className="case-picker">{t('Select a case','选择案件')}<select aria-label={t('Select a case','选择案件')} value={data.id||'custom'} onChange={e=>{const next=publicCases.find(c=>c.id===e.target.value);if(next)loadCase(next);else if(e.target.value==='demo')loadCase({...demo,id:'demo'});}}>{publicCases.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}<option value="demo">{t('Fictional demo','虚构演示')}</option>{!publicCases.some(c=>c.id===data.id)&&data.id!=='demo'&&<option value={data.id||'custom'}>{t('Imported case','导入案件')}</option>}</select></label><div className="demo-label"><i/>{data.publicRecord?t('PUBLIC COURT RECORD','公开法院记录'):data.synthetic?t('SYNTHETIC CASE','合成案件'):t('IMPORTED CASE','导入案件')}</div><nav aria-label="Primary navigation">{(Object.keys(viewNames) as View[]).map(v=>{const Icon=icons[v];return <button key={v} className={view===v?'selected':''} onClick={()=>navigate(v)} aria-current={view===v?'page':undefined}><Icon size={17}/>{viewNames[v][zh?1:0]}{view===v&&<span className="nav-indicator"/>}</button>;})}</nav><div className="sidebar-separator"/><div className="workspace-label">{t('CASE RECORD','案件记录')}</div><button className="sidebar-action" onClick={()=>setImportOpen(true)}><Upload size={16}/>{t('Import case JSON','导入案件 JSON')}</button><button className="sidebar-action" onClick={exportSnapshot}><Download size={16}/>{t('Export snapshot','导出时间切片')}</button><button className="sidebar-action" onClick={()=>loadCase({...demo,id:'demo'})}><RotateCcw size={15}/>{t('Reset demonstration','重置演示')}</button><div className="sidebar-bottom"><span className="tiny-mark">Ⅱ</span><small>{t('U.S. federal civil discovery','美国联邦民事证据开示')}</small></div></aside>
 <main><div className="breadcrumb">{t('Workspace','工作台')}<span>/</span>{data.name}<span>/</span><b>{viewNames[view][zh?1:0]}</b><span className="status"><i/>{review?t('REVIEW DEMO','回顾演示'):t('RECORD EXPLORER','记录分析')}</span></div>
 <div className="heading"><div><div className="eyebrow">{t('PROCEDURAL ANALYSIS','程序分析')}</div><h1>{view==='live'?t('Information, burden, and the next step.','信息、负担与下一步。'):view==='path'?t('Every step changes the record.','每一步都改变案件记录。'):view==='compare'?t('Compare the model’s suggested paths.','比较模型生成的路径。'):view==='frontier'?t('Compare information and cost.','比较信息与成本。'):t('A model you can examine.','可以检验的模型。')}</h1><p>{view==='live'?t('Trace information, burden, and the possibilities ahead.','追踪信息、负担与未来可能的路径。'):view==='path'?t('Reconstruct the information available at each procedural moment.','重建每个程序时点可获得的信息。'):view==='compare'?t('The model selects the least-cost path within the information tolerance and compares it with the baseline. Swap A and B to reverse the comparison.','模型选出信息容差内费用最低的路径，与基准路径比较。交换 A、B 可反转比较方向。'):view==='frontier'?t('Explore candidate paths within an information tolerance.','设定信息容差，比较候选路径。'):t('Definitions, proofs and how the calculation works.','定义、证明与计算过程。')}</p></div><div className="heading-actions"><button className="secondary" onClick={()=>setImportOpen(true)}><Upload size={15}/>{t('Import JSON','导入 JSON')}</button><button className="secondary export" onClick={exportSnapshot}><Download size={15}/>{t('Export snapshot','导出时间切片')}</button></div></div>
 {notice&&<div className="notice" role="status">{notice}<button aria-label="Dismiss" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 <div className="case-strip"><div><span className="case-dot"/><strong>{data.name}</strong><span className="case-meta">{data.jurisdiction} · {data.caseType}</span></div><label>{t('AS OF','截至')} <select aria-label="As of day" value={index} onChange={e=>{setIndex(+e.target.value);setSelectedEvent(+e.target.value);setHighlight(null);setReview(false);}}>{data.events.map((e,i)=><option key={e.id} value={i}>{e.date||`${t('Day','第')} ${e.day}${zh?' 天':''}`}</option>)}</select></label></div>
 <div className="provenance"><Info size={14}/><span>{data.synthetic?t('Synthetic case','虚构案件'):data.publicRecord?t('Public court history · retrospective reconstruction','公开法院记录 · 回溯整理'):t('Imported case','导入案件')}</span><button onClick={()=>navigate('method')}>{t('View method','查看方法')}<ArrowUpRight size={12}/></button></div>
 {(view==='live'||view==='frontier')&&!currentRun&&<section className="panel run-prompt"><h2>{t('Run the suggested paths','运行模型生成的路径')}</h2><p>{t('Calculate a comparison before exploring its results. If you changed an input, run again.','运行比较后再查看结果；如果修改了输入，需要重新运行。')}</p><button className="primary" onClick={()=>navigate('compare')}>{t('Compare paths and run','比较路径并运行')}<ArrowRight size={15}/></button></section>}
 {view==='live'&&currentRun&&<>
 <div className="mode-bar"><div className="segmented"><button className={!review?'active':''} onClick={()=>setReview(false)}>LIVE</button><button className={review?'active':''} onClick={()=>setReview(true)}>REVIEW <small>{t('demo','演示')}</small></button></div><span>{t('Information cutoff','信息截止点')}: {t('Day','第')} {state.day}{zh?' 天':''} <span className="muted">/ {state.events.length} {t('recorded events','条事件')}</span></span></div>
 {!review?<>
 <div className="kpis">{kpi(t('Information saturation','信息饱和度'),pct(state.information),t('Illustrative normalized information proxy','示例标准化信息代理指标'))}{kpi(t('Accumulated burden','累计负担'),state.unknownCosts?t('Not fully reported','未完整披露'):money(state.burden),state.unknownCosts?state.burden?t(`Known subtotal: ${money(state.burden)}; costs are incomplete.`,`已披露小计：${money(state.burden)}；费用不完整。`):t('No cost figures reported for this cutoff.','当前截止点没有已披露费用。'):`${state.hours} ${t('recorded attorney hours','记录律师工时')}`,'observed')}{kpi(t('Remaining burden','剩余负担'),compact(continuation.cost),`${compact(continuation.low)} – ${compact(continuation.high)} · ${t('scenario range','情景区间')}`)}{kpi(t('Remaining duration','剩余时长'),`${continuation.days} ${t('days','天')}`,t('Selected baseline continuation · illustrative','选定基准续行路径 · 示例'))}</div>
 <div className="dashboard-grid"><section className="panel curve-panel">{panelHead('01',t('Information / burden','信息 / 负担'),<span className="panel-tag">{t('RECORD + PROJECTION','记录 + 推演')}</span>)}<div className="chart-subtitle">{t('How much does the next step add?','下一步还能增加多少信息？')}<div className="legend"><span><i className="solid"/>{t('Record proxy','记录代理指标')}</span><span><i className="dashed"/>{t('Illustrative continuation','示例续行')}</span></div></div><Curve data={data} index={index} projection={continuation} kind={modelKind} zh={zh}/><div className="curve-bottom"><span><i className="small-dot"/>{t('TODAY','当前')} · {pct(state.information)} {t('information','信息')} / {state.unknownCosts?t('cost record incomplete','费用记录不完整'):compact(state.burden)}</span><button onClick={()=>navigate('path')}>{t('Inspect the path','查看路径')}<ArrowRight size={13}/></button></div></section>
 <section className="panel next-panel">{panelHead('02',t('Candidate action gains','候选动作增量'),<span className="panel-tag">{t('CALCULATED SCENARIOS','计算情景')}</span>)}<p className="muted section-intro">{t('Each value is the change in information score after one additional action.','每个数值表示追加一个动作后的信息评分变化。')}</p>{(Object.keys(actions) as Action[]).map(id=>{const gain=project(state.information,[id],modelKind).gain;return <div className="probability" key={id}><div><span>{label(id)}</span><b>+{(100*gain).toFixed(1)} pp</b></div><div className="bar"><i style={{width:Math.min(100,100*gain)+'%'}}/></div></div>;})}</section>
 <section className="panel marginal-panel">{panelHead('03',t('The value of the next step','下一步的价值'),<button className="text-button" onClick={()=>navigate('compare')}>{t('Compare paths','比较路径')}<ArrowUpRight size={13}/></button>)}<div className="table-scroll"><table><thead><tr><th>{t('Candidate action','候选行为')}</th><th>{t('Information gain','信息增量')}</th><th>{t('Burden','负担')}</th><th>{t('Duration','时长')}</th></tr></thead><tbody>{(Object.keys(actions) as Action[]).map(id=>{const p=project(state.information,[id],modelKind);return <tr key={id}><td><span className="action-icon"><FileText size={13}/></span>{label(id)}</td><td className="blue-text">+{p.gain.toFixed(2)}</td><td>{compact(p.cost)}</td><td>{p.days} {t('days','天')}</td></tr>;})}</tbody></table></div><div className="panel-foot">{t('Information added by each action from the selected cutoff.','从所选截止点出发，比较各行为的新增信息。')}</div></section>
 <section className="panel saturation-panel">{panelHead('04',t('Procedural saturation','程序饱和'))}<div className="saturation-state"><span className="copper-text">{state.information>=.6?t('APPROACHING SATURATION','接近饱和'):t('INFORMATION DEVELOPING','信息积累中')}</span><Activity size={20}/></div><p>{t('Explore when marginal information becomes small while burden continues.','探索边际信息趋小时，程序负担仍持续的情景。')}</p><label className="horizon">{t('Continuation horizon','续行步数')}<select value={horizon} onChange={e=>setHorizon(+e.target.value)} aria-label="Continuation horizon"><option value={1}>{t('1 action','1 步')}</option><option value={3}>{t('3 actions','3 步')}</option><option value={5}>{t('5 actions','5 步')}</option></select></label><div className="saturation-result"><strong>+{project(state.information,Array.from({length:horizon},(_,i)=>i%2?'deposition':'discovery'),modelKind).gain.toFixed(2)}</strong><span>{t('illustrative additional information','示例新增信息')}<br/><b>{compact(project(state.information,Array.from({length:horizon},(_,i)=>i%2?'deposition':'discovery'),modelKind).cost)}</b> {t('continuing burden','持续负担')}</span></div><small>{t('Continuation alternates discovery and deposition.','续行路径交替进行开示与证言录取。')}</small></section></div>
 <section className="explore-banner"><div><span className="eyebrow">{t('ORDER MATTERS','顺序有影响')}</span><h2>{t('What changes if you change the sequence?','如果改变顺序，会发生什么？')}</h2><p>{t('Hold the current state fixed. Explore two paths forward.','固定当前状态，探索两条未来路径。')}</p></div><button className="primary" onClick={()=>navigate('compare')}>{t('Compare future paths','比较未来路径')}<ArrowRight size={16}/></button></section>
 </>:<section className="panel review-panel">{panelHead('01',t('A retrospective validation preview','回顾验证预览'))}<p>{t('This completed synthetic case shows how to compare a frozen forecast with the final record.','此已结案合成样例展示如何将冻结预测与最终记录比较。')}</p><div className="table-scroll"><table><thead><tr><th>{t('Metric','指标')}</th><th>{t('Frozen demo forecast','冻结演示预测')}</th><th>{t('Synthetic realized record','合成结果记录')}</th><th>{t('Error','误差')}</th></tr></thead><tbody><tr><td>{t('Remaining burden','剩余负担')}</td><td>$82,000</td><td>$91,000</td><td>+$9,000</td></tr><tr><td>{t('Remaining duration','剩余时长')}</td><td>104 {t('days','天')}</td><td>119 {t('days','天')}</td><td>+15 {t('days','天')}</td></tr></tbody></table></div></section>}
 </>}
 {view==='path'&&<div className="path-grid"><section className="panel">{panelHead('01',t('Procedural record','程序记录'),<span className="panel-tag">{state.events.length} {t('EVENTS','条事件')}</span>)}<div className="timeline">{state.events.map((e,i)=><button className={'timeline-event '+(selectedEvent===i?'active':'')} key={e.id} onClick={()=>setSelectedEvent(i)}><span className="timeline-check"><Check size={13}/></span><span className="timeline-day">{t('DAY','第')} {e.day}{zh?' 天':''}</span><span><strong>{zh&&e.titleZh?e.titleZh:e.title}</strong><small>{e.actor} · {e.type}</small></span><b>{e.plaintiffCost===null||e.defenseCost===null?'—':compact(e.plaintiffCost+e.defenseCost)}</b></button>)}<div className="timeline-today"><span className="small-dot"/>{t('INFORMATION CUTOFF','信息截止点')} · {t('DAY','第')} {state.day}</div></div><div className="panel-foot">{t('Later events are excluded when you move the as-of selector backward.','将日期选择器移到较早时点时，后续事件会被排除。')}</div></section><section className="panel event-detail">{panelHead('02',t('Event evidence','事件证据'))}{(()=>{const e=data.events[Math.min(selectedEvent,index)];return <><span className="eyebrow">{e.id} / {t('DAY','第')} {e.day}</span><h3>{zh&&e.titleZh?e.titleZh:e.title}</h3><span className="source-tag"><FileText size={13}/>{e.sourceUrl?<a href={e.sourceUrl} target="_blank" rel="noopener noreferrer">{e.source} ↗</a>:e.source}</span>{e.sourceDate&&<small className="source-date">{t('Source published','来源发布日期')}: {e.sourceDate} · {t('retrospective reconstruction','回溯整理')}</small>}<div className="event-stats"><div><small>{t('Information increment','信息增量')}</small><strong>+{e.information.toFixed(2)}</strong><small>{t('Authored proxy','预设代理评分')}</small></div><div><small>{t('Attorney hours','律师工时')}</small><strong>{e.hours??t('Not reported','未披露')}</strong></div></div><h4>{t('Facts added to the record','记录新增事实')}</h4>{(zh&&e.factsZh?e.factsZh:e.facts).map(f=><p className="fact" key={f}><Check size={14}/>{f}</p>)}<h4>{t('Burden distribution','负担分布')}</h4><div className="split-row"><span>{t('Plaintiff','原告')}</span><b>{money(e.plaintiffCost)}</b></div><div className="split-row"><span>{t('Defense','被告')}</span><b>{money(e.defenseCost)}</b></div></>;})()}</section><section className="panel path-curve">{panelHead('03',t('Information state evolution','信息状态演变'))}<Curve data={data} index={index} projection={continuation} kind={modelKind} zh={zh}/></section></div>}
 {view==='compare'&&<><div className="compare-intro"><span><GitBranch size={16}/>{t('Both paths start at','两条路径都始于')} {t('Day','第')} {state.day} · {pct(state.information)} {t('information','信息')}</span><button className="secondary" onClick={()=>setSwapped(value=>!value)}><RotateCcw size={14}/>{t('Swap paths','交换路径')}</button></div><div className="compare-grid">{[a,b].map((p,col)=>{const isOptimized=col===0?!swapped:swapped;return <section className="panel sequence-card" key={col}>{panelHead(col===0?'A':'B',isOptimized?t('Least-cost candidate','最低费用候选'):t('Baseline path','基准路径'))}<div className="sequence-start"><span className="small-dot"/>{t('CURRENT STATE','当前状态')}</div><ol className="automatic-path" aria-label={t(`Path ${col===0?'A':'B'}`,`路径 ${col===0?'A':'B'}`)}>{p.path.map((id,i)=><li className="automatic-step" key={i}><span>{String(i+1).padStart(2,'0')}</span><strong>{label(id)}</strong></li>)}</ol>{!p.path.length&&<p className="automatic-empty">{t('Proceed on the current record.','使用当前记录，不再追加动作。')}</p>}<p className="automatic-caption">{isOptimized?t(`Lowest cost among ${all.length} paths within ε = ${epsilon.toFixed(2)} of baseline information.`,`在 ${all.length} 条路径中，选出相对基准信息容差 ε = ${epsilon.toFixed(2)} 内费用最低者。`):t('Deposition → discovery → motion is the reference continuation.','以证言录取 → 开示 → 动议作为基准续行路径。')}</p></section>;})}</div>
 <section className="panel run-panel"><div><h2>{t('Run these two paths','运行这两条路径')}</h2><p>{t('Path A','路径 A')}: {pathA.length?pathA.map(label).join(' → '):t('No further actions','不再采取动作')}<br/>{t('Path B','路径 B')}: {pathB.length?pathB.map(label).join(' → '):t('No further actions','不再采取动作')}</p><small>{data.docket} · {t('Cutoff','截止点')}: {data.events[index].date||`Day ${state.day}`}</small></div><div className="model-summary"><small>{t('Model','模型')}</small><span>Heisenberg H₅</span><button className="text-button" onClick={()=>navigate('method')}>{t('Read the method','查看方法')}</button></div><button className="primary" onClick={()=>setExecution({key:runKey,result:runModel(data,index,epsilon,pathA,pathB,modelKind)})}>{t('Run model','运行模型')}<ArrowRight size={15}/></button><div className="run-status" role="status">{currentRun?t(`Calculated ${currentRun.candidateCount} candidate paths from ${currentRun.eventCount} events.`,`已用 ${currentRun.eventCount} 条事件计算 ${currentRun.candidateCount} 条候选路径。`):execution?t('Inputs changed. Run again to update the results.','输入已改变，请重新运行以更新结果。'):t('Suggested paths ready. Run to calculate results.','模型已生成路径。点击运行后显示结果。')}</div>{currentRun&&<div className="run-results"><div><small>{t('Path difference · A minus B','路径差 · A 减 B')}</small><strong>{(100*currentRun.orderGap.gain).toFixed(2)} pp</strong><span>{t('Information proxy','信息代理指标')}</span></div><div><small>{t('Scenario cost difference','情景费用差')}</small><strong>{money(currentRun.orderGap.cost)}</strong><span>{currentRun.orderGap.days} {t('days difference','天时长差')}</span></div><div><small>{t('Paths on the frontier','前沿路径数')}</small><strong>{currentRun.frontier.length} / {currentRun.candidateCount}</strong><button className="text-button" onClick={()=>navigate('frontier')}>{t('Inspect paths','查看路径')}</button></div><details><summary>{t('Order representation and assumptions','顺序表示与假设')}</summary><p>{t('The calculation uses four action coordinates and a shared central term. Method explains the pairing, formulas and assumptions.','计算使用四个动作坐标和一个共享中心项。配对、公式和假设详见 Method。')}</p><p>{t('Engine','引擎')}: {currentRun.model}</p><code>H₅ A: {JSON.stringify(currentRun.heisenbergA)}<br/>H₅ B: {JSON.stringify(currentRun.heisenbergB)}<br/>{t('Full pairwise audit','完整成对坐标审计')} A: {JSON.stringify(currentRun.signatureA)}<br/>B: {JSON.stringify(currentRun.signatureB)}</code><button className="text-button" onClick={()=>navigate('method')}>{t('How the model is applied','模型怎样应用')}</button></details></div>}</section>
{currentRun&&<><div className="compare-grid">{[currentRun.a,currentRun.b].map((p,i)=><section className="panel sequence-card" key={i}>{panelHead(i===0?'A':'B',t('Calculated result','计算结果'))}<div className="sequence-stats"><div><span>{t('Information gained','新增信息')}</span><strong>+{(100*p.gain).toFixed(1)} pp</strong></div><div><span>{t('Future burden','未来负担')}</span><strong>{compact(p.cost)}</strong></div><div><span>{t('Duration','时长')}</span><strong>{p.days} {t('days','天')}</strong></div></div><p className="scenario-range">{t('Burden scenario range','负担情景区间')}: {compact(p.low)} – {compact(p.high)}</p></section>)}</div><section className="order-effect"><div><span className="eyebrow">{t('PATH A − PATH B','路径 A − 路径 B')}</span><h2>{t('Path comparison','路径比较')}</h2><p>{[...pathA].sort().join() === [...pathB].sort().join()?t('The same actions in a different order.','相同动作，不同顺序。'):t('Action sets differ. This comparison combines action selection and ordering.','行为集合不同，此比较同时包含行为选择与排序差异。')}</p></div><div className="effect-metrics"><div><strong>{a.gain-b.gain>=0?'+':''}{(a.gain-b.gain).toFixed(3)}</strong><span>{t('Information','信息')}</span></div><div><strong>{a.cost-b.cost>0?'+':''}{compact(a.cost-b.cost)}</strong><span>{t('Burden','负担')}</span></div><div><strong>{a.days-b.days>0?'+':''}{a.days-b.days}d</strong><span>{t('Duration','时长')}</span></div></div></section><section className="panel">{panelHead('03',t('Who carries the burden?','谁承担程序负担？'))}<div className="table-scroll"><table><thead><tr><th>{t('Path','路径')}</th><th>{t('Plaintiff','原告')}</th><th>{t('Defense','被告')}</th><th>{t('Total','总计')}</th></tr></thead><tbody>{[a,b].map((p,i)=><tr key={i}><td>{i===0?'A':'B'}</td><td>{money(p.plaintiff)}</td><td>{money(p.defense)}</td><td>{money(p.cost)}</td></tr>)}</tbody></table></div></section></>}</>}
 {view==='frontier'&&currentRun&&<><div className="frontier-toolbar"><label>{t('Information tolerance','信息容差')}<input type="range" min="0" max=".10" step=".01" value={epsilon} onChange={e=>{setEpsilon(+e.target.value);setHighlight(null);}}/><b>ε = {epsilon.toFixed(2)}</b></label><span>{all.length} {t('enumerated paths · up to 3 distinct actions','条枚举路径 · 最多 3 个不重复行为')}</span></div><div className="kpis three">{kpi(t('Baseline continuation','基准续行路径'),compact(comparison.baseline.cost),t('Deposition → discovery → motion','证言录取 → 开示 → 动议'))}{kpi(t('Least burden within tolerance','容差内最低负担'),compact(comparison.best.cost),`${pct(comparison.best.quality)} ${t('information proxy','信息代理指标')}`)}{kpi(t('Potential burden gap','潜在负担差'),compact(comparison.gap),t('Across 41 candidate paths','比较 41 条候选路径'))}</div><div className="frontier-grid"><section className="panel">{panelHead('01',t('Procedural frontier','程序前沿'),<span className="panel-tag">{t('ILLUSTRATIVE','示例')}</span>)}<div className="chart-subtitle">{t('More information. Less burden. Explore the tradeoff.','探索信息与负担之间的权衡。')}</div><FrontierChart points={all} edge={edge} selected={highlight||comparison.best} baseline={comparison.baseline} threshold={comparison.baseline.quality-epsilon} onSelect={setHighlight} zh={zh}/><div className="panel-foot">{t('Dots are selectable paths. The frontier is nondominated within this finite candidate set.','圆点代表可选择的路径。前沿仅相对于此有限候选集合非支配。')}</div></section><section className="panel frontier-detail">{panelHead('02',t('Inspect a path','查看路径'))}{(()=>{const p=highlight||comparison.best;return <><span className="eyebrow">{highlight?t('SELECTED CANDIDATE','所选候选'):t('LOWEST FEASIBLE BURDEN','最低可行负担')}</span><h3>{p.path.length?p.path.map(label).join(' → '):t('Proceed on current record','使用当前记录')}</h3><div className="split-row"><span>{t('Information proxy','信息代理指标')}</span><b>{pct(p.quality)}</b></div><div className="split-row"><span>{t('Future burden','未来负担')}</span><b>{compact(p.cost)}</b></div><div className="split-row"><span>{t('Duration','时长')}</span><b>{p.days}d</b></div><div className="feasibility">{p.quality>=comparison.baseline.quality-epsilon-1e-9?<Check size={15}/>:<Info size={15}/>} {p.quality>=comparison.baseline.quality-epsilon-1e-9?t('Within selected tolerance','在所选容差内'):t('Below the required proxy level','低于所需代理指标水平')}</div><button className="primary" onClick={()=>navigate('compare')}>{t('Return to comparison','返回路径比较')}<ArrowRight size={15}/></button><p>{t('The comparison uses the least-cost candidate and the baseline.','路径比较使用最低费用候选与基准路径。')}</p></>;})()}</section></div></>}
 {view==='method'&&<Method zh={zh}/>}
 <footer><span>Ⅱ SecondOrder Procedure</span><span>{productVersion}</span></footer>
 </main></div>
 {importOpen&&<div className="modal-backdrop" onClick={()=>setImportOpen(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="import-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setImportOpen(false);if(e.key==='Tab'){const buttons=e.currentTarget.querySelectorAll<HTMLButtonElement>('button');const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><button className="modal-close" aria-label="Close import" autoFocus onClick={()=>setImportOpen(false)}><X size={18}/></button><span className="eyebrow">{t('LOCAL CASE INGESTION','本地案件导入')}</span><h2 id="import-title">{t('Bring a structured record.','导入结构化案件记录。')}</h2><p>{t('This version accepts case JSON, up to 1 MB and 200 chronological events. Files are processed in this browser only and are not retained after refresh.','本版本接受最大 1 MB、最多 200 条按时间排列事件的案件 JSON。文件仅在浏览器内处理，刷新后不保留。')}</p>{notice&&<div className="notice" role="alert">{notice}</div>}<div className="import-actions"><button className="secondary" onClick={()=>download('secondorder-case-template.json',demo)}><Download size={15}/>{t('Download template','下载模板')}</button><button className="primary" onClick={()=>upload.current?.click()}><Upload size={15}/>{t('Choose JSON file','选择 JSON 文件')}</button></div><code>schemaVersion · name · jurisdiction · caseType · synthetic · events[]</code><small>{t('Event fields: id, day, type, actor, title, source, facts[], plaintiffCost, defenseCost, hours, information.','事件字段：id、day、type、actor、title、source、facts[]、plaintiffCost、defenseCost、hours、information。')}</small></section></div>}
 <input ref={upload} type="file" accept=".json,application/json" hidden onChange={e=>{if(e.target.files?.[0])void importFile(e.target.files[0]);}}/>
 </div>;
}
function Curve({data,index,projection,kind,zh}:{data:CaseData;index:number;projection:Projection;kind:ModelKind;zh:boolean}){
 const s=stateAt(data,index),timeAxis=!!data.publicRecord,maxCost=timeAxis?Math.max(1,(s.day+projection.days)*1.15):Math.max(160000,(s.burden+projection.cost)*1.15),left=48,right=650,top=25,bottom=245;
 const x=(v:number)=>left+v/maxCost*(right-left),y=(v:number)=>bottom-v*(bottom-top);let cost=0,info=0;
 const record=[[x(0),y(0)],...s.events.map(e=>{cost+=(e.plaintiffCost??0)+(e.defenseCost??0);info+=e.information;return [x(timeAxis?e.day:cost),y(info)];})];
 const future=projection.path.map((_,i)=>project(s.information,projection.path.slice(0,i+1),kind));const projected=[[x(timeAxis?s.day:s.burden),y(s.information)],...future.map(p=>[x(timeAxis?s.day+p.days:s.burden+p.cost),y(p.quality)])];const line=(points:number[][])=>points.map((p,i)=>(i?'L':'M')+p.join(',')).join(' ');
 const start=projected[0];
 return <svg viewBox="0 0 700 300" className="curve" role="img" aria-label={zh?'信息与累计负担曲线，虚线为示例推演':'Information versus cumulative burden, with illustrative continuation'}><defs><linearGradient id="underCurve" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#315b99" stopOpacity=".10"/><stop offset="1" stopColor="#315b99" stopOpacity=".005"/></linearGradient></defs>{[0,.25,.5,.75,1].map(v=><g key={v}><line x1={left} x2={right} y1={y(v)} y2={y(v)} stroke="#e7ecf1"/><text x={left-12} y={y(v)+4} textAnchor="end" className="axis">{pct(v)}</text></g>)}{[0,.25,.5,.75,1].map(v=><g key={v}><line x1={x(maxCost*v)} x2={x(maxCost*v)} y1={top} y2={bottom} stroke="#f1f3f5"/><text x={x(maxCost*v)} y={bottom+24} textAnchor="middle" className="axis">{timeAxis?Math.round(maxCost*v)+'d':compact(maxCost*v)}</text></g>)}<text x={left} y="13" className="axis">{zh?'信息代理指标':'Information proxy'}</text><path d={line(record)+` L ${record.at(-1)![0]},${bottom} L ${left},${bottom} Z`} fill="url(#underCurve)"/><path d={line(record)} fill="none" stroke="#315b99" strokeWidth="2.6" strokeLinejoin="round"/><path d={line(projected)} fill="none" stroke="#829bb8" strokeWidth="2" strokeDasharray="5 5"/>{record.slice(1).map((p,i)=><circle key={i} cx={p[0]} cy={p[1]} r="3" fill="#fff" stroke="#315b99"><title>{s.events[i].title}: {pct(s.events.slice(0,i+1).reduce((sum,e)=>sum+e.information,0))}</title></circle>)}<line x1={start[0]} x2={start[0]} y1={start[1]+12} y2={bottom} stroke="#bb704f" strokeDasharray="3 4"/><circle cx={start[0]} cy={start[1]} r="6" fill="#bb704f" stroke="white" strokeWidth="3"/><text x={start[0]} y={start[1]-15} textAnchor="middle" className="today-label">{zh?'当前':'TODAY'}</text><text x="350" y="291" textAnchor="middle" className="axis">{timeAxis?(zh?'从首条所选记录起的天数':'Days since first included event'):(zh?'累计程序负担（美元）':'Cumulative procedural burden (USD)')}</text></svg>;
}
function FrontierChart({points,edge,selected,baseline,threshold,onSelect,zh}:{points:Projection[];edge:Projection[];selected:Projection;baseline:Projection;threshold:number;onSelect:(p:Projection)=>void;zh:boolean}){
 const maxCost=Math.max(...points.map(p=>p.cost))*1.1,minQuality=Math.min(...points.map(p=>p.quality))-.04,x=(v:number)=>54+v/maxCost*550,y=(v:number)=>250-(v-minQuality)/(1-minQuality)*210;
 return <svg viewBox="0 0 660 310" className="frontier-chart" role="group" aria-label={zh?'可交互的程序前沿':'Interactive procedural frontier'}>{[minQuality,.75,.85,.95,1].filter(v=>v>=minQuality).map(v=><g key={v}><line x1="54" x2="605" y1={y(v)} y2={y(v)} stroke="#e5ebf1"/><text x="43" y={y(v)+4} textAnchor="end" className="axis">{pct(v)}</text></g>)}{[0,.25,.5,.75,1].map(v=><text key={v} x={x(v*maxCost)} y="276" textAnchor="middle" className="axis">{compact(v*maxCost)}</text>)}<text x="54" y="20" className="axis">{zh?'最终信息代理指标':'Final information proxy'}</text><line x1="54" x2="605" y1={y(threshold)} y2={y(threshold)} stroke="#bb704f" strokeDasharray="4 4"/><text x="605" y={y(threshold)+15} textAnchor="end" className="axis">{zh?'容差阈值':'Tolerance threshold'}</text><path d={edge.map((p,i)=>(i?'L':'M')+x(p.cost)+','+y(p.quality)).join(' ')} fill="none" stroke="#315b99" strokeWidth="2"/>{points.map((p,i)=><circle key={i} cx={x(p.cost)} cy={y(p.quality)} r={p.cost===selected.cost&&p.quality===selected.quality?7:4} fill={p.cost===selected.cost&&p.quality===selected.quality?'#bb704f':edge.includes(p)?'#315b99':'#c6d2df'} stroke="white" strokeWidth="1.5" tabIndex={0} role="button" aria-label={`${p.path.join(' then ')||'Current record'}, ${money(p.cost)}, ${pct(p.quality)} information`} onClick={()=>onSelect(p)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(p);}}}><title>{p.path.join(' → ')||'Current record'} · {money(p.cost)} · {pct(p.quality)}</title></circle>)}<rect x={x(baseline.cost)-5} y={y(baseline.quality)-5} width="10" height="10" fill="none" stroke="#bb704f"/><text x="330" y="304" textAnchor="middle" className="axis">{zh?'未来负担（美元）':'Future burden (USD)'}</text></svg>;
}

